// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package futuredb

import (
	"time"
)

type Appointment struct {
	ID        int32     `json:"id"`
	UserID    int32     `json:"user_id"`
	StartsAt  time.Time `json:"starts_at"`
	EndsAt    time.Time `json:"ends_at"`
	TrainerID int32     `json:"trainer_id"`
}

type AppointmentSlot struct {
	StartsAt time.Time `json:"starts_at"`
}
